[[libsimplecommunicationencoder]]
arch = "x86_64"
git-tree-sha1 = "e43f37509be6117ab30b9c31260db27da82d2ee6"
os = "windows"

    [[libsimplecommunicationencoder.download]]
    sha256 = "5157842691b1dfa1699c0be4e57be02d777f88b49ef0e8c1277886fa9f396294"
    url = "https://github.com/HyperSphereStudio/libsimplecommunicationencoder_jll/releases/download/libsimplecommunicationencoder-v1.0.0+0/libsimplecommunicationencoder.v1.0.0.x86_64-w64-mingw32.tar.gz"
