# Autogenerated wrapper script for libsimplecommunicationencoder_jll for x86_64-w64-mingw32
export libsimplecommunicationencoder

JLLWrappers.@generate_wrapper_header("libsimplecommunicationencoder")
JLLWrappers.@declare_library_product(libsimplecommunicationencoder, "libsimplecommunicationencoder.dll")
function __init__()
    JLLWrappers.@generate_init_header()
    JLLWrappers.@init_library_product(
        libsimplecommunicationencoder,
        "bin\\libsimplecommunicationencoder.dll",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@generate_init_footer()
end  # __init__()
